### ISSUE TITLE
pypi source release for 0.1.0 is missing requirements.txt

### ISSUE THREAD

**Issue by apmorton** [vast-data/vastdb_sdk#47] opened 2024-04-11 16:10 UTC
```
Downloading https://pypi.io/packages/source/v/vastdb/vastdb-0.1.0.tar.gz
Success
Extracting download
source tree in: /home/conda/feedstock_root/build_artifacts/vastdb_1712819329121/work
export PREFIX=/home/conda/feedstock_root/build_artifacts/vastdb_1712819329121/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/vastdb_1712819329121/_build_env
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/vastdb_1712819329121/work
Using pip 24.0 from $PREFIX/lib/python3.12/site-packages/pip (python 3.12)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-build-tracker-cg4y7fii
Initialized build tracking at /tmp/pip-build-tracker-cg4y7fii
Created build tracker: /tmp/pip-build-tracker-cg4y7fii
Entered build tracker: /tmp/pip-build-tracker-cg4y7fii
Created temporary directory: /tmp/pip-install-kwnwe30q
Created temporary directory: /tmp/pip-ephem-wheel-cache-8nxd_ll_
Processing $SRC_DIR
  Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-cg4y7fii'
  Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
  Running command python setup.py egg_info
  Created temporary directory: /tmp/pip-pip-egg-info-g1l9gukk
  Preparing metadata (setup.py): started
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/vastdb_1712819329121/work/setup.py", line 34, in <module>
      install_requires=open('requirements.txt').read().strip().split('\n'),
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  error: subprocess-exited-with-error
```

**Comment by rz-vastdata** [comment] 2024-04-11 20:46
Many thanks for reporting this issue!

**Comment by rz-vastdata** [comment] 2024-04-13 06:07
@apmorton Would #10 help resolve this issue?

**Comment by apmorton** [comment] 2024-04-13 09:38
I believe so

**Comment by rz-vastdata** [comment] 2024-04-14 12:17
Will be released soon as `v0.1.1`.

**Comment by rz-vastdata** [comment] 2024-04-16 18:25
https://pypi.org/project/vastdb/0.1.1/ is now available.

@apmorton could you please try to adapt https://github.com/conda-forge/vastdb-feedstock/pull/1 to see if the previous issue was resolved?

**Comment by rz-vastdata** [comment] 2024-04-17 09:39
IIUC, https://github.com/conda-forge/vastdb-feedstock/pull/2 passed - does it mean that the issue is resolved?

**Closed** 2024-04-17 11:46 UTC
